// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvlwpbtixjpzsjiozhtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2bHdwYnRpeGpwenNqaW96aHRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTIxMjcsImV4cCI6MjA3NDIyODEyN30.LL15zNbB7kGwz44mznL7DW2MgXvB2hyGqVFhTp1ZE90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});